"""Executable conformance helpers for the language-neutral Agent Local Node wire."""

from .conformance import build_conformance_document, validate_conformance_document
from .channel import (
    CHANNEL_PROTOCOL_VERSION,
    MAX_CHANNEL_LINE_BYTES,
    MAX_PAIRING_MATERIAL_BYTES,
    ChannelViolation,
    build_client_hello,
    build_request_frame,
    build_response_frame,
    build_server_hello,
    derive_session_key,
    parse_pairing_material,
    parse_request_frame,
    parse_response_frame,
    validate_pairing_material,
    verify_client_hello,
    verify_server_hello,
)
from .protocol import (
    ERROR_CODES,
    ERROR_RETRYABLE,
    MAX_PAYLOAD_BYTES,
    MAX_REQUEST_BYTES,
    MAX_RESPONSE_BYTES,
    OPERATIONS,
    PROTOCOL_VERSION,
    ProtocolViolation,
    ReplayLedger,
    authorize_request,
    canonical_json_bytes,
    derive_idempotency_slot,
    digest_json,
    parse_request_line,
    parse_response_line,
    parse_strict_json_line,
    validate_request,
    validate_response,
)

__all__ = [
    "ERROR_CODES",
    "ERROR_RETRYABLE",
    "MAX_PAYLOAD_BYTES",
    "MAX_REQUEST_BYTES",
    "MAX_RESPONSE_BYTES",
    "OPERATIONS",
    "PROTOCOL_VERSION",
    "ProtocolViolation",
    "CHANNEL_PROTOCOL_VERSION",
    "MAX_CHANNEL_LINE_BYTES",
    "MAX_PAIRING_MATERIAL_BYTES",
    "ChannelViolation",
    "ReplayLedger",
    "authorize_request",
    "build_conformance_document",
    "build_client_hello",
    "build_request_frame",
    "build_response_frame",
    "build_server_hello",
    "canonical_json_bytes",
    "derive_idempotency_slot",
    "digest_json",
    "derive_session_key",
    "parse_pairing_material",
    "parse_request_frame",
    "parse_request_line",
    "parse_response_frame",
    "parse_response_line",
    "parse_strict_json_line",
    "validate_pairing_material",
    "validate_conformance_document",
    "validate_request",
    "validate_response",
    "verify_client_hello",
    "verify_server_hello",
]
